name: Resource submissions

on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on:
      labels: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo "Labels:"
          for label in ${{ fromJson(github.event.issue.labels) }}; do
            echo $label.name
          done
