name: Resource submissions

on:
  issues:
    types:
      - opened
  workflow_dispatch:

jobs:
  label_issue:
    runs-on:
      labels: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          echo ${{ github.event.issue.labels[0].name }}
        run: |
          echo ${{ github.event.issue.labels[1].name }}
