name: Resource submissions

on:
  issues:
    types:
      - opened
  workflow_dispatch:

jobs:
  label_issue:
    runs-on:
      labels: ubuntu-latest
    steps:
      - name: echo 0
        if: contains(github.event.issue.labels.*.name, 'Submission')
        run: |
          echo ${{ github.event.issue.labels[0].name }}

      - name: echo 1
        if: contains(github.event.issue.labels.*.name, 'Submissio')
        run: |
          echo ${{ github.event.issue.labels[0].name }}
